---
abstract: 'Utilities related to prime numbers, including fast generators / sievers'
author:
  - 'Dana A Jacobsen <dana@acm.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-Prime-Util
no_index:
  directory:
    - t
    - inc
requires:
  Exporter: 5.562
  Test::More: 0.45
  XSLoader: 0.01
  perl: 5.006002
version: 0.01
