---
abstract: 'Utilities related to prime numbers, including fast sieves and factoring'
author:
  - 'Dana A Jacobsen <dana@acm.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  Test::More: 0.45
  bignum: 0.22
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.82, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-Prime-Util
no_index:
  directory:
    - t
    - inc
recommends:
  Math::BigInt::GMP: 0
  Math::MPFR: 2.03
  Math::Prime::Util::GMP: 0.16
requires:
  Bytes::Random::Secure: 0.23
  Carp: 0
  Config: 0
  Exporter: 5.562
  Math::BigFloat: 1.59
  Math::BigInt: 1.88
  Tie::Array: 0
  XSLoader: 0.01
  base: 0
  perl: 5.006002
resources:
  homepage: https://github.com/danaj/Math-Prime-Util
  license: http://dev.perl.org/licenses/
  repository: https://github.com/danaj/Math-Prime-Util
version: 0.35
