---
abstract: 'Utilities related to prime numbers, including fast sieves and factoring'
author:
  - 'Dana A Jacobsen <dana@acm.org>'
build_requires:
  Test::More: 0.45
  bignum: 0.22
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-Prime-Util
no_index:
  directory:
    - t
    - inc
recommends:
  Math::BigInt::GMP: 0
requires:
  Carp: 0
  Config: 0
  Exporter: 5.562
  Math::BigFloat: 1.59
  Math::BigInt: 1.88
  Tie::Array: 0
  XSLoader: 0.01
  base: 0
  perl: 5.006002
version: 0.14
